"""empty message

Revision ID: 56479d71c495
Revises: e643645f12d3
Create Date: 2023-09-06 22:28:38.707890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56479d71c495'
down_revision = 'e643645f12d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_later', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_later', schema=None) as batch_op:
        batch_op.drop_column('movie_id')

    # ### end Alembic commands ###
