"""empty message

Revision ID: e643645f12d3
Revises: 
Create Date: 2023-09-01 21:03:01.026663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e643645f12d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('watch_later',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('release_date', sa.String(length=20), nullable=True),
    sa.Column('runtime', sa.Integer(), nullable=True),
    sa.Column('vote_average', sa.Float(), nullable=True),
    sa.Column('original_language', sa.String(length=10), nullable=True),
    sa.Column('poster_path', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watch_later')
    op.drop_table('user')
    # ### end Alembic commands ###
